name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  call-tests:
    uses: ./.github/workflows/_tests.yml

  publish:
    name: Build and publish
    needs: call-tests
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          # This differentiates the cache for each version in your matrix
          cache-suffix: "python${{ matrix.python-version }}-${{ runner.os }}"

      - name: Set up Python
        run: uv python install 3.12

      - name: Build and Publish
        run: |
          uv build
          uv publish
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.6.1
        with:
          files: dist/*
          generate_release_notes: true
